---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudChaps Resorts Virtual Private Network internet Gateways and routes.

Parameters:
  Env:
    Description: Environment name
    Type: String
    AllowedValues:
      - DEV
      - STAGE
      - PROD

  VPCName:
    Description: VPC Name
    Type: String

Resources:
  # Create Internet Gateway to connnect Public Subnet to the Internet
  ESPublicInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-IGW"
        - Key: Project
          Value: CloudChaps_Resorts
        - Key: Environment
          Value: !Ref Env
        - Key: Owner
          Value: !Ref AWS::AccountId

  # Attach Internet Gateway to the VPC
  ESAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Fn::ImportValue: !Sub "${Env}-VPC-ID"
      InternetGatewayId: !Ref ESPublicInternetGateway

Outputs:

  InternetGatewayID:
    Description: Internet Gateway ID
    Value: !Ref ESPublicInternetGateway
    Export:
      Name: !Sub "${Env}-IGW-ID"


