---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudChaps Resorts Virtual Private Network internet Gateways and routes.

Parameters:
  Env:
    Description: Environment name
    Type: String
    AllowedValues:
      - DEV
      - STAGE
      - PROD

  VPCName:
    Description: VPC Name
    Type: String

Resources:
  # Create Internet Gateway to connnect Public Subnet to the Internet
  ESPublicInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-IGW"
        - Key: Project
          Value: CloudChaps_Resorts
        - Key: Environment
          Value: !Ref Env
        - Key: Owner
          Value: !Ref AWS::AccountId

  # Attach Internet Gateway to the VPC
  ESAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Fn::ImportValue: !Sub "${Env}-VPC-ID"
      InternetGatewayId: !Ref ESPublicInternetGateway
  
  # Create Public Route Table
  ESPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: 
        Fn::ImportValue: !Sub "${Env}-VPC-ID"
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-PublicRT"
        - Key: Project
          Value: CloudChaps_Resorts
        - Key: Environment
          Value: !Ref Env
        - Key: Owner
          Value: !Ref AWS::AccountId

  # Create Private Route Tables
  ESPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Fn::ImportValue: !Sub "${Env}-VPC-ID"
      Tags:
        - Key: Name
          Value: !Sub "${VPCName}-PrivateRouteTable"
        - Key: Project
          Value: CloudChaps
        - Key: Environment
          Value: !Ref Env
        - Key: Owner
          Value: !Ref AWS::AccountId

Outputs:

  InternetGatewayID:
    Description: Internet Gateway ID
    Value: !Ref ESPublicInternetGateway
    Export:
      Name: !Sub "${Env}-IGW-ID"
  
  RouteTableID:
    Description: Public Route Table ID
    Value: !Ref ESPublicRouteTable
    Export:
      Name: !Sub "${Env}-PublicRT-ID"
  
  PrivateRouteTableID:
    Description: Private Route Table ID
    Value: !Ref ESPrivateRouteTable
    Export:
      Name: !Sub "${Env}-PrivateRT-ID"


